catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.MovieList.as_view(), name='index'),
    path('filter/<str:model>/<slug:model_url>/', views.FilterMovieList.as_view(), name='filter_movies_list'),
    path('multiple_filter/', views.MultipleFilterMovieList.as_view(), name='multiple_filter_movies_list'),
    path('search/', views.SearchMovieList.as_view(), name='search_movies_list'),
    path('movie_detail/<slug:movie_url>/', views.MovieDetail.as_view(), name='movie_detail'),
    path('add_rating/', views.AddStarRating.as_view(), name='add_rating'),
]

moviedom/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path('', include('catalog.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')
    description = models.TextField(blank=True, verbose_name='Описание')

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')
    description = models.TextField(blank=True, verbose_name='Описание')

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')

    class Meta:
        verbose_name = 'страну'
        verbose_name_plural = 'страны'

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')
    photo = models.ImageField(upload_to='directors', blank=True, null=True, verbose_name='фото')
    about = models.TextField(blank=True, verbose_name='биография')

    class Meta:
        verbose_name = 'режиссера'
        verbose_name_plural = 'режиссеры'

    def save(self, *args, **kwargs):
        if not self.photo:
            self.photo = 'none_avatar.png'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField(max_length=255, verbose_name='ФИО')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')
    photo = models.ImageField(upload_to='actors', blank=True, null=True, verbose_name='Фото')
    about = models.TextField(blank=True, verbose_name='Биография')

    class Meta:
        verbose_name = 'актера'
        verbose_name_plural = 'актеры'

    def save(self, *args, **kwargs):
        if not self.photo:
            self.photo = 'none_avatar.png'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Movie(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name='movies',
        null=True,
        verbose_name='Категория',
    )
    title = models.CharField(max_length=255, verbose_name='Название')
    url = models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')
    tagline = models.CharField(max_length=255, blank=True, verbose_name='Слоган')
    description = models.TextField(verbose_name='Описание')
    poster = models.ImageField(upload_to='movies', verbose_name='Постер')
    year = models.PositiveSmallIntegerField(default=timezone.now().year, verbose_name='Год')
    country = models.ManyToManyField(Country, related_name='movies', verbose_name='Страна')
    director = models.ManyToManyField(Director, related_name='movies', verbose_name='Режиссер')
    actors = models.ManyToManyField(Actor, related_name='movies', verbose_name='Актеры')
    genre = models.ManyToManyField(Genre, related_name='movies', verbose_name='Жанры')
    world_premiere = models.DateField(null=True, verbose_name='Премьера в мире')
    budget = models.PositiveIntegerField(default=0, help_text='сумма в $', verbose_name='Бюджет')
    fees = models.PositiveIntegerField(default=0, help_text='сумма в $', verbose_name='Сборы')
    moderation = models.BooleanField(default=False, verbose_name='Модерация')

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'фильмы'
        ordering = ('-id',)

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'movie_url': self.url})

    def get_review(self):
        return self.reviews.filter(parent__isnull=True).prefetch_related('reviews')

    def __str__(self):
        return self.title


class RatingStar(models.Model):
    star_value = models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Значение')
    url = models.SlugField(unique=True, max_length=255, verbose_name='Ссылка')

    class Meta:
        verbose_name = 'звезду рейтинга'
        verbose_name_plural = 'здезды рейтинга'
        ordering = ('-star_value',)

    def save(self, *args, **kwargs):
        if not self.url:
            self.url = f'{self.value}_star'
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.star_value)


class Rating(models.Model):
    ip = models.CharField(max_length=15, verbose_name='IP адрес')
    star = models.ForeignKey(
        RatingStar,
        related_name='rating',
        on_delete=models.CASCADE,
        verbose_name='Звезда',
    )
    movie = models.ForeignKey(
        Movie,
        related_name='rating',
        on_delete=models.CASCADE,
        verbose_name='Фильм',
    )

    class Meta:
        verbose_name = 'рейтинг'
        verbose_name_plural = 'рейтинги'

    def __str__(self):
        return f'{self.movie} - {self.star}'


class Review(models.Model):
    posted = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(
        Movie,
        related_name='reviews',
        on_delete=models.CASCADE,
        verbose_name='Фильм',
    )
    email = models.EmailField(blank=True, verbose_name='Почта')
    name = models.CharField(max_length=255, verbose_name='Имя')
    text = models.TextField(max_length=5000, verbose_name='Текст')
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='reviews',
        blank=True,
        null=True,
        verbose_name='Ответ на комментарий',
    )

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        ordering = ('-posted',)

    def __str__(self):
        return (
                f'{self.name} про "{self.movie}" - '
                f'{self.posted.strftime("%d %b %Yг. %H:%M")}'
        )

catalog/forms.py
from django import forms
from django.db.models import Count

from catalog.models import Review, Rating, RatingStar

from snowpenguin.django.recaptcha3.fields import ReCaptchaField


class ReviewForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    captcha = ReCaptchaField()

    class Meta:
        model = Review
        fields = ('text', 'name', 'email', 'captcha')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control border', 'id': 'contactcomment'}),
            'name': forms.TextInput(attrs={'class': 'form-control border'}),
            'email': forms.EmailInput(attrs={'class': 'form-control border'}),
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.annotate(__count=Count('*')),
        widget=forms.RadioSelect(),
        empty_label=None,
    )

    class Meta:
        model = Rating
        fields = ('star',)

catalog/views.py
import re

from django.db.models import Q, Count, Avg
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import ReviewForm, RatingForm
from .models import Movie, Category, Genre, Country, Director, Actor, Rating, RatingStar


class MovieList(ListView):
    model = Movie
    paginate_by = 9
    template_name = 'catalog/movies_list.html'
    extra_context = {'page': 'index', 'params': '?page', 'index_page': True}

    def get_queryset(self):
        return (
            self.model.objects.filter(moderation=True)
            .annotate(rating_av=Avg('rating__star__star_value'))
        )


class FilterMovieList(MovieList):
    models = {
        'category': Category,
        'genre': Genre,
        'country': Country,
        'director': Director,
        'actor': Actor,
        'star': RatingStar,
    }

    def get_queryset(self):
        try:
            model = self.models[self.kwargs['model']]
            model_instance = model.objects.get(url=self.kwargs['model_url'])
        except KeyError:
            raise Http404
        except model.DoesNotExist:
            raise Http404(f'{model._meta.verbose_name} не найдено')
        if not isinstance(model_instance, RatingStar):
            self.kwargs['title'] = model_instance.name
            movies = model_instance.movies.annotate(rating_av=Avg('rating__star__star_value'))
        else:
            self.kwargs['title'] = f'{model_instance.star_value}'
            movies = (
                Movie.objects.annotate(rating_av=Avg('rating__star__star_value'))
                .filter(rating_av=model_instance.star_value)
            )
        return movies.filter(moderation=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['model'] = self.kwargs['model']
        context['page'] = 'category'
        context['title'] = self.kwargs['title']
        context['params'] = '?page'
        return context


class MultipleFilterMovieList(MovieList):
    def get_queryset(self):
        genre = self.request.GET.getlist('genre')
        year = self.request.GET.getlist('year')
        if genre and not year:
            queryset = Movie.objects.filter(genre__in=genre)
        elif not genre and year:
            queryset = Movie.objects.filter(year__in=year)
        elif genre and year:
            queryset = Movie.objects.filter(genre__in=genre, year__in=year)
        return (
            queryset.distinct().filter(moderation=True)
            .annotate(rating_av=Avg('rating__star__star_value'))
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        params = re.search(r'/multiple_filter/(.+)', self.request.get_full_path())
        context['params'] = params.group(1) + '&page'
        return context


class SearchMovieList(MovieList):
    def get_queryset(self):
        try:
            query = self.request.GET['search'].strip()
        except KeyError:
            query = ''
        movies = Movie.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return movies.filter(moderation=True).annotate(rating_av=Avg('rating__star__star_value'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        context['page'] = 'search'
        context['search_query'] = query if query else 'Ничего не найдено'
        context['title'] = f'{query}'
        context['params'] = f'?search={query}&page'
        return context


class MovieDetail(DetailView):
    form_class = ReviewForm

    def get_object(self, queryset=None):
        movie = (
            Movie.objects.prefetch_related('country', 'director', 'actors', 'genre')
            .select_related('category')
            .annotate(reviews_count=Count('reviews'))
            .get(url=self.kwargs['movie_url'])
        )
        self.kwargs['title'] = movie.category.name
        return movie

    def post(self, request):
        movie = self.get_object()
        form = self.form_class(request.POST)
        if form.is_valid():
            new_review = form.save(commit=False)
            if request.POST.get('parent', None):
                new_review.parent_id = int(request.POST.get("parent"))
            new_review.movie = movie
            new_review.save()
            return redirect('movie_detail', movie.url)
        return render(request, self.template_name, {'movie': movie, 'form': form})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'category'
        context['title'] = self.kwargs['title']
        context['star_form'] = RatingForm()
        context['form'] = ReviewForm()
        return context


class AddStarRating(View):
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))},
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

catalog/templates/catalog/base.html
{% load static i18n %}
{% load catalog_tags %}
{% load recaptcha3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- //Meta tag Keywords -->
    {% get_current_language as LANGUAGE_CODE %}
    <title>
        {% block title %}
            MovieDom - {% if LANGUAGE_CODE == 'ru' %}портал о кино{% else %}portal about cinema{% endif %}
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">
    <!-- //Fonts -->
    {% recaptcha_init %}
    {% recaptcha_ready action_name='homepage' %}
    <style>
            .bg1 {
                background-color: rgba(0, 0, 0, 0);
                margin-top: 0px;
                background-image:
                {% if page != 'search' %}
                    {% if title == 'Фильмы' or title == 'Movies' %}url("{% static 'images/movies_banner.jpg' %}");
                    {% elif title == 'Cartoons' or title == 'Мультфильмы' %}url("{% static 'images/cartoons_banner.jpg' %}");
                    {% elif title == 'Series' or title == 'Сериалы' %}url("{% static 'images/series_banner.webp' %}");
                    {% elif title == 'Documentary' or title == 'Документалки' %}url("{% static 'images/documentary_banner.jpg' %}");
                    {% else %}url("{% static 'images/main_banner.jpg' %}");
                    {% endif %}
                {% else %}
                    url("{% static 'images/main_banner.jpg' %}");
                {% endif %}
            }
    </style>
</head>

<body>
    <div id="page" class="page"><!-- mian-content -->
        <div class="main-banner bg bg1" id="home">
            <!-- header -->
            {% include 'catalog/includes/header.html' %}
            <!-- //header -->
            <!--/banner-->
            <div class="banner-info">
                <h3 class="mb-4 editContent">
                    {% if page == 'index' or page == 'category' or page == 'search' %}
                        {% trans 'Все о кино' %}
                    {% endif %}
                </h3>
                <div class="ban-buttons"></div>
            </div>
            <!--// banner-inner -->
        </div>
        <!--//main-content-->
        <!---->
        <ol class="breadcrumb editContent"></ol>
        <!---->
        <!-- banner -->
        <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
            <div class="container-fluid py-md-3">
                <div class="row">
                    {% if index_page %}
                        <div class="side-bar col-lg">
                            {% include 'catalog/includes/sidebar.html' %}
                        </div>
                    {% endif %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </section>
        <!-- //contact -->
        <!-- footer -->
        {% include 'catalog/includes/footer.html' %}
        <!-- //footer -->
        <div class="cpy-right py-3">
            <div class="container">
                <div class="row">
                    <p class="col-md-10 text-left">© 2021 MovieDom. All rights reserved | Design by
                        <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
                    </p>
                    <!-- move top icon -->
                    <a href="" class="move-top text-right col-md-2"><span class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
                    <!-- //move top icon -->
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
    <script src='https://twitter.github.io/hogan.js/builds/3.0.1/hogan-3.0.1.js'></script>
</body>
</html>

catalog/templates/catalog/movie_detail.html
{% extends 'catalog/base.html' %}
{% load i18n static %}
{% load catalog_filters %}
{% load humanize %}

{% block title %}{{movie}} | {{block.super}}{% endblock %}

{% block content %}
    <div class="left-ads-display col-lg-10 ml-5">
        <div class="row">
            <div class="" width="100px">
                <img src="{{movie.poster.url}}" class="" alt="" width="325" height="450">
            </div>
            <div class="desc1-right col-md-7 pl-lg-4">
                <h2 class="editContent" style="outline: none; cursor: inherit;">
                    {{movie}}
                </h2>
                <ul>
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Год' %}:</span>
                            <a href="/multiple_filter/?year={{movie.year}}" class="related-obj">{{movie.year}}</a>
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Страна' %}:</span>
                            {% for country in movie.country.all %}
                                <a href="{% url 'filter_movies_list' model='country' model_url=country.url %}" class="related-obj">
                                    {{country}}{% if not forloop.last %}, {% endif %}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    {% if movie.tagline %}
                        <li style="list-style: none">
                            <span><span style="font-weight:700;">{% trans 'Слоган' %}:</span> «{{movie.tagline}}»</span>
                        </li>
                    {% endif %}
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Режиссер' %}:</span>
                            {% for director in movie.director.all %}
                                <a href="{% url 'filter_movies_list' 'director' director.url %}" class="related-obj">
                                    {{director}}{% if not forloop.last %}, {% endif %}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Актеры' %}:</span>
                            {% for actor in movie.actors.all %}
                                <a href="{% url 'filter_movies_list' 'actor' actor.url %}" class="related-obj">
                                    {{actor}}{% if not forloop.last %}, {% endif %}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Жанр' %}:</span>
                            {% for genre in movie.genre.all %}
                                <a href="{% url 'filter_movies_list' 'genre' genre.url %}" class="related-obj">
                                    {{genre}}{% if not forloop.last %}, {% endif %}
                                </a>
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none">
                        <span>
                            <span style="font-weight:700;">{% trans 'Премьера в мире' %}:</span> {{movie.world_premiere}}
                        </span>
                    </li>
                    {% if budget %}
                        <li style="list-style: none">
                            <span><span style="font-weight:700;">{% trans 'Бюджет' %}:</span> ${{movie.budget|intcomma}}</span>
                        </li>
                    {% endif %}
                    {% if fees %}
                        <li style="list-style: none">
                            <span><span style="font-weight:700;">{% trans 'Сборы в прокате' %}:</span> ${{movie.fees|intcomma}}</span>
                        </li>
                    {% endif %}

                    <li style="list-style: none">
                        <form action="{% url 'add_rating' %}" method="post" name="rating">
                            <span style="font-weight:700;">{% trans 'Рейтинг' %}</span>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="rating">
                                {% for id, value in star_form.fields.star.choices %}
                                    <input id="rating{{ value }}" type="radio" name="star" value="{{ id }}">
                                    <label for="rating{{ value }}">{{ id }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent"></span>
                        </form>
                    </li>
                </ul>

                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                        <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                        <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>

        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">{% trans 'О фильме' %} {{movie}}</h3>
            <div>
                <p class="">{{movie.description|safe}}</p>
            </div>
        </div>
        <hr>
        {% include 'catalog/includes/comments_section.html' %}
    </div>

    <script src="{% static 'js/script.js' %}"></script>
    <script>
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `;
        }
    </script>
{% endblock %}

catalog/templates/catalog/movies_list.html
{% extends 'catalog/base.html' %}
{% load i18n catalog_filters %}

{% block title %}
    {% if title %}
        {% if page != 'search' %}
            {{title}} {% if model == 'star' %}&#9733;{% endif %} | {{block.super}}
        {% else %}
             {% trans 'Поиск' %} - "{{title}}" | {{block.super}}
        {% endif %}
    {% else %}
        {{block.super}}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% if movie_list %}
                {% for movie in movie_list %}
                    <div class="col-md-4 product-men">
                        <div class="product-shoe-info editContent text-center mt-lg-4" >
                            <div class="men-thumb-item">
                                <img src="{{movie.poster.url}}" alt="" width="259px" height="325px">
                            </div>
                            <div class="item-info-product">
                                <h4 class="">
                                    <a href="{{movie.get_absolute_url}}" class="editContent" >{{movie}}</a>
                                </h4>
                                <div class="product_price">
                                    <div class="grid-price">
                                        {% if movie.tagline %}
                                            <span class="money editContent" >«{{movie.tagline}}»</span>
                                        {% endif %}
                                    </div>
                                </div>
                                <ul class="stars">
                                    {% for _ in movie.rating_av|make_range %}
                                        <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                    {% endfor %}
                                    {% for _ in movie.rating_av|change_number_sign|add:5|make_range %}
                                        <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            {% else %}
                <h2 class="ml-5">
                    {% trans 'Не найдено ни одного фильма' %}
                    {% if page == 'search' %}{% trans 'по запросу' %} "{{title}}"{% endif %}
                </h2>
            {% endif %}
        </div>
        <br>
        <div class="d-flex justify-content-center">
            {% include 'catalog/includes/pagination.html' %}
        </div>
    </div>
{% endblock %}